meta-tizen: weston: get rid of bogus mesa dependency
Weston requires virtual/egl dependency, with is provided by either
mesa or mesa_gl package.

Making weston dependent of mesa is too strict, as it doesn't allow
using mesa_gl. So, it produces bitbake errors when compiling on
arm using a different 3D driver, like Raspberry PI userland:

ERROR: Multiple .bb files are due to be built which each provide virtual/libgles2 (/devel/tizen-distro/metapi/recipes-graphics/userland/userland_git.bb /devel/tizen-distro/meta-tizen/meta-tizen-adaptation/meta/recipes-graphics/mesa/mesa_10.3.4.bb).
 This usually means one provides something the other doesn't and should.
ERROR: Multiple .bb files are due to be built which each provide virtual/egl (/devel/tizen-distro/metapi/recipes-graphics/userland/userland_git.bb /devel/tizen-distro/meta-tizen/meta-tizen-adaptation/meta/recipes-graphics/mesa/mesa_10.3.4.bb).
 This usually means one provides something the other doesn't and should.

On the other hand, weston is already dependent on virtual/egl, with is
provided by mesa (or mesa_gl). So, there's no need to keep this bogus
dependency here. Just get rid of it.

Change-Id: I750e951ddba9ba0e6aafe7de3ba17393a3eff7a3
(From meta-tizen rev: 138ef21b7661624c23e1fd0a4e68e211664da175)

Signed-off-by: Mauro Carvalho Chehab <mchehab@osg.samsung.com>
Reviewed-By: Derek Foreman <derekf@osg.samsung.com>